In [22]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats

In [3]:
df=pd.read_csv(r"C:\Users\USER\Downloads\train_ctrUa4K.csv")

In [4]:
df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [5]:
df.shape

(614, 13)

In [6]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [7]:
df.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       614.000000         614.000000  592.000000         600.00000   
mean       5403.459283        1621.245798  146.412162         342.00000   
std        6109.041673        2926.248369   85.587325          65.12041   
min         150.000000           0.000000    9.000000          12.00000   
25%        2877.500000           0.000000  100.000000         360.00000   
50%        3812.500000        1188.500000  128.000000         360.00000   
75%        5795.000000        2297.250000  168.000000         360.00000   
max       81000.000000       41667.000000  700.000000         480.00000   

       Credit_History  
count      564.000000  
mean         0.842199  
std          0.364878  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          1.000000  
max          1.000000

In [8]:
df.drop('Loan_ID',axis=1,inplace=True)

In [9]:
null_cols = ['Credit_History', 'Self_Employed', 'LoanAmount','Dependents', 'Loan_Amount_Term', 'Gender', 'Married']

In [10]:
for col in null_cols:
     df[col]=df[col].fillna(df[col].dropna().mode().values[0])

In [11]:
df.isna().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [12]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [13]:
df['Dependents']=le.fit_transform(df['Dependents'])
df['Property_Area']=le.fit_transform(df['Property_Area'])
df['Gender']=le.fit_transform(df['Gender'])
df['Married']=le.fit_transform(df['Married'])
df['Education']=le.fit_transform(df['Education'])
df['Self_Employed']=le.fit_transform(df['Self_Employed'])
df['Loan_Status']=le.fit_transform(df['Loan_Status'])

In [14]:
df.head()

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        0           0          0              0             5849   
1       1        1           1          0              0             4583   
2       1        1           0          0              1             3000   
3       1        1           0          1              0             2583   
4       1        0           0          0              0             6000   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0       120.0             360.0             1.0   
1             1508.0       128.0             360.0             1.0   
2                0.0        66.0             360.0             1.0   
3             2358.0       120.0             360.0             1.0   
4                0.0       141.0             360.0             1.0   

   Property_Area  Loan_Status  
0              2            1  
1              0            0  
2              2            1  
3              2            1  
4              2            1

In [15]:
X=df.drop(['Loan_Status'],axis=1)
X.head()

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        0           0          0              0             5849   
1       1        1           1          0              0             4583   
2       1        1           0          0              1             3000   
3       1        1           0          1              0             2583   
4       1        0           0          0              0             6000   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0       120.0             360.0             1.0   
1             1508.0       128.0             360.0             1.0   
2                0.0        66.0             360.0             1.0   
3             2358.0       120.0             360.0             1.0   
4                0.0       141.0             360.0             1.0   

   Property_Area  
0              2  
1              0  
2              2  
3              2  
4              2

In [16]:
y=df['Loan_Status']
y.head()

0    1
1    0
2    1
3    1
4    1
Name: Loan_Status, dtype: int32

In [17]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42,test_size=0.2)

# model1

In [18]:
from sklearn.linear_model import LogisticRegression
log_model=LogisticRegression(max_iter=400)
log_model=log_model.fit(X_train,y_train)
y_pred=log_model.predict(X_test)

In [19]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [20]:
confusion_matrix(y_test,y_pred)

array([[18, 25],
       [ 1, 79]], dtype=int64)

In [21]:
print('Accuracy=',accuracy_score(y_test,y_pred))

Accuracy= 0.7886178861788617


In [39]:
submission=pd.read_csv(r"C:\Users\USER\Downloads\sample_submission_49d68Cx.csv")

In [40]:
test_df=pd.read_csv(r"C:\Users\USER\Downloads\test_lAUu6dG.csv")
test_df.drop('Loan_ID',axis=1,inplace=True)

null_cols = ['Credit_History', 'Self_Employed', 'LoanAmount','Dependents', 'Loan_Amount_Term', 'Gender']

In [41]:
for col in null_cols:
     test_df[col]=test_df[col].fillna(test_df[col].dropna().mode().values[0])

In [42]:
test_df.isna().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
dtype: int64

In [43]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [44]:
test_df['Dependents']=le.fit_transform(test_df['Dependents'])
test_df['Property_Area']=le.fit_transform(test_df['Property_Area'])
test_df['Gender']=le.fit_transform(test_df['Gender'])
test_df['Married']=le.fit_transform(test_df['Married'])
test_df['Education']=le.fit_transform(test_df['Education'])
test_df['Self_Employed']=le.fit_transform(test_df['Self_Employed'])

In [45]:
test_df.head()

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        1           0          0              0             5720   
1       1        1           1          0              0             3076   
2       1        1           2          0              0             5000   
3       1        1           2          0              0             2340   
4       1        0           0          1              0             3276   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                  0       110.0             360.0             1.0   
1               1500       126.0             360.0             1.0   
2               1800       208.0             360.0             1.0   
3               2546       100.0             360.0             1.0   
4                  0        78.0             360.0             1.0   

   Property_Area  
0              2  
1              2  
2              2  
3              2  
4              2

In [50]:
pred_test=log_model.predict(test_df)
submission['Loan_Status']=pred_test
submission['Loan_Status'].replace(0,'N',inplace=True)
submission['Loan_Status'].replace(1,'Y',inplace=True)

In [51]:
pd.DataFrame(submission, columns=['Loan_ID','Loan_Status']).to_csv('logistic.csv')

# model2

In [48]:
from sklearn.svm import SVC
svm_cls=SVC(kernel='linear')
svm_cls=svm_cls.fit(X_train,y_train)
y_pred_svm=svm_cls.predict(X_test)

In [23]:
confusion_matrix(y_test,y_pred_svm)

array([[17, 26],
       [ 0, 80]], dtype=int64)

In [24]:
print('Accuracy=',accuracy_score(y_test,y_pred_svm))

Accuracy= 0.7886178861788617


In [25]:
svm_cls1=SVC(kernel='rbf')
svm_cls1=svm_cls1.fit(X_train,y_train)
y_pred_svm1=svm_cls1.predict(X_test)

In [26]:
print('Accuracy=',accuracy_score(y_test,y_pred_svm1))

Accuracy= 0.6504065040650406


# model3

In [27]:
from sklearn.tree import DecisionTreeClassifier
dt_cls=DecisionTreeClassifier()
dt_cls=dt_cls.fit(X_train,y_train)
y_pred_dt=dt_cls.predict(X_test)

In [28]:
print('Accuracy=',accuracy_score(y_test,y_pred_dt))

Accuracy= 0.6991869918699187


# model4

In [43]:
from sklearn.ensemble import RandomForestClassifier
rf_cls= RandomForestClassifier()
rf_cls=rf_cls.fit(X_train,y_train)
y_pred_rf=rf_cls.predict(X_test)

In [30]:
print('Accuracy=',accuracy_score(y_test,y_pred_rf))

Accuracy= 0.7723577235772358


# model5

In [31]:
from sklearn.model_selection import KFold

In [32]:
kfold_validator=KFold(10)
for train_index,test_index in kfold_validator.split(X,y):
    print('Training Index:',train_index)
    print('Testing Index:',test_index)

Training Index: [ 62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79
  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97
  98  99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115
 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133
 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151
 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169
 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187
 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205
 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223
 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241
 242 243 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259
 260 261 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 277
 278 279 280 281 282 283 284 285 286 287 288 289 290 291 292 293 294 295
 296 297 298 299 300 301 302 303 30

In [33]:
from sklearn.model_selection import cross_val_score
cv_result=cross_val_score(log_model,X,y,cv=kfold_validator)

In [34]:
cv_result

array([0.77419355, 0.83870968, 0.74193548, 0.77419355, 0.78688525,
       0.83606557, 0.85245902, 0.85245902, 0.80327869, 0.83606557])

In [35]:
np.mean(cv_result)

0.8096245372818613

In [ ]:
pred_test=_model.predict(test_df)
submission['Loan_Status']=pred_test
submission['Loan_Status'].replace(0,'N',inplace=True)
submission['Loan_Status'].replace(1,'Y',inplace=True)

# model6

In [36]:
from sklearn.model_selection import StratifiedKFold

In [37]:
skfold_validator=StratifiedKFold(n_splits=10)

In [38]:
for train_index,test_index in skfold_validator.split(X,y):
    print('Training Index:',train_index)
    print('Testing Index:',test_index)

Training Index: [ 53  54  57  62  63  64  65  66  69  71  72  73  74  75  76  77  78  79
  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97
  98  99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115
 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133
 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151
 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169
 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187
 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205
 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223
 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241
 242 243 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259
 260 261 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 277
 278 279 280 281 282 283 284 285 286 287 288 289 290 291 292 293 294 295
 296 297 298 299 300 301 302 303 30

In [39]:
cv_result=cross_val_score(log_model,X,y,cv=skfold_validator)

In [40]:
cv_result

array([0.80645161, 0.82258065, 0.74193548, 0.75806452, 0.78688525,
       0.78688525, 0.85245902, 0.85245902, 0.80327869, 0.83606557])

In [41]:
np.mean(cv_result)

0.8047065044949762

In [42]:
model = RandomForestClassifier(n_estimators=300, criterion='entropy',max_features='sqrt',min_samples_leaf=10,random_state=100).fit(X_train,y_train)

In [44]:
prediction2 = model.predict(X_test)

In [45]:
print(accuracy_score(y_test,prediction2))

0.7886178861788617


In [46]:
[int(x) for x in np.linspace(start=200, stop=2000, num=10)]

[200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000]

In [47]:
from sklearn.model_selection import RandomizedSearchCV

n_estimators = [int(x) for x in np.linspace(start=200, stop=2000, num=10)]
max_features = ['auto', 'sqrt','log2']
max_depth = [int(x) for x in np.linspace(10,1000,10)]
min_samples_split = [2,5,10,14]
min_samples_leaf = [1,2,4,6,8]

random_grid = {'n_estimators':n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split':min_samples_split,
               'min_samples_leaf':min_samples_leaf,
               'criterion':['entropy','gini']}

In [48]:
rf = RandomForestClassifier()
rf_randomcv = RandomizedSearchCV(estimator=rf, param_distributions = random_grid, n_iter=100, cv=3,verbose=2,random_state=100,n_jobs=-1)

rf_randomcv.fit(X_train,y_train)

Fitting 3 folds for each of 100 candidates, totalling 300 fits


RandomizedSearchCV(cv=3, estimator=RandomForestClassifier(), n_iter=100,
                   n_jobs=-1,
                   param_distributions={'criterion': ['entropy', 'gini'],
                                        'max_depth': [10, 120, 230, 340, 450,
                                                      560, 670, 780, 890,
                                                      1000],
                                        'max_features': ['auto', 'sqrt',
                                                         'log2'],
                                        'min_samples_leaf': [1, 2, 4, 6, 8],
                                        'min_samples_split': [2, 5, 10, 14],
                                        'n_estimators': [200, 400, 600, 800,
                                                         1000, 1200, 1400, 1600,
                                                         1800, 2000]},
                   random_state=100, verbose=2)

In [49]:
rf_randomcv.best_params_

{'n_estimators': 200,
 'min_samples_split': 10,
 'min_samples_leaf': 1,
 'max_features': 'sqrt',
 'max_depth': 560,
 'criterion': 'gini'}

In [50]:
best_random_grid = rf_randomcv.best_estimator_

In [51]:
y_pred = best_random_grid.predict(X_test)

In [52]:
accuracy_score(y_test,y_pred)

0.7804878048780488

In [53]:
[rf_randomcv.best_params_['min_samples_leaf'],rf_randomcv.best_params_['min_samples_leaf']+1,
                                  rf_randomcv.best_params_['min_samples_leaf']+2,
                                  rf_randomcv.best_params_['min_samples_leaf']+4]

[1, 2, 3, 5]